/* Generated by Cython 0.12 on Tue Dec 29 13:40:00 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#else
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
  #define PyDict_Contains(d,o)   PySequence_Contains(d,o)
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyUnicode_Type
  #define PyString_CheckExact          PyUnicode_CheckExact
#else
  #define PyBytes_Type                 PyString_Type
  #define PyBytes_CheckExact           PyString_CheckExact
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceTrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceDivide(x,y)
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__cpyamf__amf3

#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; const long n; const char* encoding; const char is_unicode; const char is_str; const char intern; } __Pyx_StringTabEntry; /*proto*/


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString          PyString_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyString_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyString_AsString
#else
#define __Pyx_PyBytes_FromString          PyBytes_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyBytes_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyBytes_AsString
#endif

#define __Pyx_PyBytes_FromUString(s)      __Pyx_PyBytes_FromString((char*)s)
#define __Pyx_PyBytes_AsUString(s)        ((unsigned char*) __Pyx_PyBytes_AsString(s))

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

#if !defined(T_PYSSIZET)
#if PY_VERSION_HEX < 0x02050000
#define T_PYSSIZET T_INT
#elif !defined(T_LONGLONG)
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))  ? T_INT  : \
        ((sizeof(Py_ssize_t) == sizeof(long)) ? T_LONG : -1))
#else
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))          ? T_INT      : \
        ((sizeof(Py_ssize_t) == sizeof(long))         ? T_LONG     : \
        ((sizeof(Py_ssize_t) == sizeof(PY_LONG_LONG)) ? T_LONGLONG : -1)))
#endif
#endif


#if !defined(T_ULONGLONG)
#define __Pyx_T_UNSIGNED_INT(x) \
        ((sizeof(x) == sizeof(unsigned char))  ? T_UBYTE : \
        ((sizeof(x) == sizeof(unsigned short)) ? T_USHORT : \
        ((sizeof(x) == sizeof(unsigned int))   ? T_UINT : \
        ((sizeof(x) == sizeof(unsigned long))  ? T_ULONG : -1))))
#else
#define __Pyx_T_UNSIGNED_INT(x) \
        ((sizeof(x) == sizeof(unsigned char))  ? T_UBYTE : \
        ((sizeof(x) == sizeof(unsigned short)) ? T_USHORT : \
        ((sizeof(x) == sizeof(unsigned int))   ? T_UINT : \
        ((sizeof(x) == sizeof(unsigned long))  ? T_ULONG : \
        ((sizeof(x) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))))
#endif
#if !defined(T_LONGLONG)
#define __Pyx_T_SIGNED_INT(x) \
        ((sizeof(x) == sizeof(char))  ? T_BYTE : \
        ((sizeof(x) == sizeof(short)) ? T_SHORT : \
        ((sizeof(x) == sizeof(int))   ? T_INT : \
        ((sizeof(x) == sizeof(long))  ? T_LONG : -1))))
#else
#define __Pyx_T_SIGNED_INT(x) \
        ((sizeof(x) == sizeof(char))  ? T_BYTE : \
        ((sizeof(x) == sizeof(short)) ? T_SHORT : \
        ((sizeof(x) == sizeof(int))   ? T_INT : \
        ((sizeof(x) == sizeof(long))  ? T_LONG : \
        ((sizeof(x) == sizeof(PY_LONG_LONG))   ? T_LONGLONG : -1)))))
#endif

#define __Pyx_T_FLOATING(x) \
        ((sizeof(x) == sizeof(float)) ? T_FLOAT : \
        ((sizeof(x) == sizeof(double)) ? T_DOUBLE : -1))

#if !defined(T_SIZET)
#if !defined(T_ULONGLONG)
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))  ? T_UINT  : \
        ((sizeof(size_t) == sizeof(unsigned long)) ? T_ULONG : -1))
#else
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))          ? T_UINT      : \
        ((sizeof(size_t) == sizeof(unsigned long))         ? T_ULONG     : \
        ((sizeof(size_t) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))
#endif
#endif

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static PyObject *__pyx_empty_bytes;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;


/* Type declarations */

/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":26
 *     cdef int at_eof(self) except? -1
 *     cdef inline Py_ssize_t remaining(self) except? -1
 *     cdef int seek(self, Py_ssize_t pos, int mode=*) except? -1             # <<<<<<<<<<<<<<
 *     cdef object getvalue(self)
 *     cdef int peek(self, char **buf, Py_ssize_t size) except? -1
 */

struct __pyx_opt_args_6cpyamf_4util_19cBufferedByteStream_seek {
  int __pyx_n;
  int mode;
};

/* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":72
 *     return size
 * 
 * cdef int _decode_int(cBufferedByteStream stream, long *ret, int sign=0) except? -1:             # <<<<<<<<<<<<<<
 *     cdef int n = 0
 *     cdef long result = 0
 */

struct __pyx_opt_args_6cpyamf_4amf3__decode_int {
  int __pyx_n;
  int sign;
};

/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":60
 * 
 * 
 * cdef class cIndexedCollection:             # <<<<<<<<<<<<<<
 *     cdef int use_hash
 *     cdef PyObject **data
 */

struct __pyx_obj_6cpyamf_4util_cIndexedCollection {
  PyObject_HEAD
  struct __pyx_vtabstruct_6cpyamf_4util_cIndexedCollection *__pyx_vtab;
  int use_hash;
  PyObject **data;
  PyObject *refs;
  Py_ssize_t size;
  Py_ssize_t length;
};

/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":76
 * 
 * 
 * cdef class cIndexedMap(cIndexedCollection):             # <<<<<<<<<<<<<<
 *     cdef object mapped
 * 
 */

struct __pyx_obj_6cpyamf_4util_cIndexedMap {
  struct __pyx_obj_6cpyamf_4util_cIndexedCollection __pyx_base;
  PyObject *mapped;
};

/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":9
 * 
 * 
 * cdef class cBufferedByteStream:             # <<<<<<<<<<<<<<
 *     cdef char _endian
 *     cdef char *buffer
 */

struct __pyx_obj_6cpyamf_4util_cBufferedByteStream {
  PyObject_HEAD
  struct __pyx_vtabstruct_6cpyamf_4util_cBufferedByteStream *__pyx_vtab;
  char _endian;
  char *buffer;
  int closed;
  Py_ssize_t pos;
  Py_ssize_t size;
  Py_ssize_t length;
};


/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":60
 * 
 * 
 * cdef class cIndexedCollection:             # <<<<<<<<<<<<<<
 *     cdef int use_hash
 *     cdef PyObject **data
 */

struct __pyx_vtabstruct_6cpyamf_4util_cIndexedCollection {
  int (*_increase_size)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *);
  void (*_clear)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *);
  int (*clear)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *);
  PyObject *(*_ref)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *, PyObject *);
  PyObject *(*getByReference)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *, Py_ssize_t);
  Py_ssize_t (*getReferenceTo)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *, PyObject *);
  Py_ssize_t (*append)(struct __pyx_obj_6cpyamf_4util_cIndexedCollection *, PyObject *);
};
static struct __pyx_vtabstruct_6cpyamf_4util_cIndexedCollection *__pyx_vtabptr_6cpyamf_4util_cIndexedCollection;


/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":9
 * 
 * 
 * cdef class cBufferedByteStream:             # <<<<<<<<<<<<<<
 *     cdef char _endian
 *     cdef char *buffer
 */

struct __pyx_vtabstruct_6cpyamf_4util_cBufferedByteStream {
  Py_ssize_t (*tell)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  int (*close)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  int (*write)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, char *, Py_ssize_t);
  int (*complain_if_closed)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  int (*_increase_buffer)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, Py_ssize_t);
  int (*has_available)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, Py_ssize_t);
  int (*read)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, char **, Py_ssize_t);
  int (*at_eof)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  Py_ssize_t (*remaining)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  int (*seek)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, Py_ssize_t, struct __pyx_opt_args_6cpyamf_4util_19cBufferedByteStream_seek *__pyx_optional_args);
  PyObject *(*getvalue)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  int (*peek)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, char **, Py_ssize_t);
  int (*truncate)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, Py_ssize_t);
  int (*consume)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *);
  int (*unpack_int)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, int, long *);
  int (*unpack_uint)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, int, unsigned long *);
  int (*pack_int)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, int, long);
  int (*pack_uint)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, int, unsigned long);
  int (*read_uchar)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned char *);
  int (*read_char)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, char *);
  int (*read_ushort)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned short *);
  int (*read_short)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, short *);
  int (*read_ulong)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned long *);
  int (*read_long)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, long *);
  int (*read_24bit_uint)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned long *);
  int (*read_24bit_int)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, long *);
  int (*write_uchar)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned char);
  int (*write_char)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, char);
  int (*write_ushort)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned short);
  int (*write_short)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, short);
  int (*write_ulong)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned long);
  int (*write_long)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, long);
  int (*write_24bit_uint)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned long);
  int (*write_24bit_int)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, long);
  PyObject *(*read_utf8_string)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, unsigned int);
  int (*write_utf8_string)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, PyObject *);
  int (*read_double)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, double *);
  int (*write_double)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, double);
  int (*read_float)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, float *);
  int (*write_float)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, float);
  int (*append)(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, PyObject *);
};
static struct __pyx_vtabstruct_6cpyamf_4util_cBufferedByteStream *__pyx_vtabptr_6cpyamf_4util_cBufferedByteStream;


/* "/Users/nick/projects/pyamf-git/cpyamf/util.pxd":76
 * 
 * 
 * cdef class cIndexedMap(cIndexedCollection):             # <<<<<<<<<<<<<<
 *     cdef object mapped
 * 
 */

struct __pyx_vtabstruct_6cpyamf_4util_cIndexedMap {
  struct __pyx_vtabstruct_6cpyamf_4util_cIndexedCollection __pyx_base;
  PyObject *(*getMappedByReference)(struct __pyx_obj_6cpyamf_4util_cIndexedMap *, Py_ssize_t);
  Py_ssize_t (*map)(struct __pyx_obj_6cpyamf_4util_cIndexedMap *, PyObject *, PyObject *);
};
static struct __pyx_vtabstruct_6cpyamf_4util_cIndexedMap *__pyx_vtabptr_6cpyamf_4util_cIndexedMap;

#ifndef CYTHON_REFNANNY
  #define CYTHON_REFNANNY 0
#endif

#if CYTHON_REFNANNY
  typedef struct {
    void (*INCREF)(void*, PyObject*, int);
    void (*DECREF)(void*, PyObject*, int);
    void (*GOTREF)(void*, PyObject*, int);
    void (*GIVEREF)(void*, PyObject*, int);
    void* (*SetupContext)(const char*, int, const char*);
    void (*FinishContext)(void**);
  } __Pyx_RefNannyAPIStruct;
  static __Pyx_RefNannyAPIStruct *__Pyx_RefNanny = NULL;
  static __Pyx_RefNannyAPIStruct * __Pyx_RefNannyImportAPI(const char *modname) {
    PyObject *m = NULL, *p = NULL;
    void *r = NULL;
    m = PyImport_ImportModule((char *)modname);
    if (!m) goto end;
    p = PyObject_GetAttrString(m, (char *)"RefNannyAPI");
    if (!p) goto end;
    r = PyLong_AsVoidPtr(p);
  end:
    Py_XDECREF(p);
    Py_XDECREF(m);
    return (__Pyx_RefNannyAPIStruct *)r;
  }
  #define __Pyx_RefNannySetupContext(name)           void *__pyx_refnanny = __Pyx_RefNanny->SetupContext((name), __LINE__, __FILE__)
  #define __Pyx_RefNannyFinishContext()           __Pyx_RefNanny->FinishContext(&__pyx_refnanny)
  #define __Pyx_INCREF(r) __Pyx_RefNanny->INCREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_DECREF(r) __Pyx_RefNanny->DECREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GOTREF(r) __Pyx_RefNanny->GOTREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GIVEREF(r) __Pyx_RefNanny->GIVEREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_XDECREF(r) do { if((r) != NULL) {__Pyx_DECREF(r);} } while(0)
#else
  #define __Pyx_RefNannySetupContext(name)
  #define __Pyx_RefNannyFinishContext()
  #define __Pyx_INCREF(r) Py_INCREF(r)
  #define __Pyx_DECREF(r) Py_DECREF(r)
  #define __Pyx_GOTREF(r)
  #define __Pyx_GIVEREF(r)
  #define __Pyx_XDECREF(r) Py_XDECREF(r)
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) do { if((r) != NULL) {__Pyx_GIVEREF(r);} } while(0)
#define __Pyx_XGOTREF(r) do { if((r) != NULL) {__Pyx_GOTREF(r);} } while(0)

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static INLINE char __Pyx_PyInt_AsChar(PyObject *);

static INLINE short __Pyx_PyInt_AsShort(PyObject *);

static INLINE int __Pyx_PyInt_AsInt(PyObject *);

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static INLINE long __Pyx_PyInt_AsLong(PyObject *);

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
/* Module declarations from cpyamf.util */

static PyTypeObject *__pyx_ptype_6cpyamf_4util_cBufferedByteStream = 0;
static PyTypeObject *__pyx_ptype_6cpyamf_4util_cIndexedCollection = 0;
static PyTypeObject *__pyx_ptype_6cpyamf_4util_cIndexedMap = 0;
/* Module declarations from cpyamf.amf3 */

static Py_ssize_t __pyx_f_6cpyamf_4amf3__encode_int(long, char **); /*proto*/
static int __pyx_f_6cpyamf_4amf3__decode_int(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *, long *, struct __pyx_opt_args_6cpyamf_4amf3__decode_int *__pyx_optional_args); /*proto*/
#define __Pyx_MODULE_NAME "cpyamf.amf3"
int __pyx_module_is_main_cpyamf__amf3 = 0;

/* Implementation of cpyamf.amf3 */
static PyObject *__pyx_builtin_OverflowError;
static PyObject *__pyx_builtin_MemoryError;
static PyObject *__pyx_builtin_RuntimeError;
static char __pyx_k_1[] = "Out of range";
static char __pyx_k_3[] = "Unable to decode int";
static char __pyx_k_4[] = "\nC-extension for L{pyamf.amf3} Python module in L{PyAMF<pyamf>}.\n\n@since: 0.4\n";
static char __pyx_k_5[] = "encode_int (line 108)";
static char __pyx_k_6[] = "decode_int (line 125)";
static char __pyx_k__sign[] = "sign";
static char __pyx_k__stream[] = "stream";
static char __pyx_k____main__[] = "__main__";
static char __pyx_k____test__[] = "__test__";
static char __pyx_k__decode_int[] = "decode_int";
static char __pyx_k__encode_int[] = "encode_int";
static char __pyx_k__read_uchar[] = "read_uchar";
static char __pyx_k__MemoryError[] = "MemoryError";
static char __pyx_k__RuntimeError[] = "RuntimeError";
static char __pyx_k__OverflowError[] = "OverflowError";
static PyObject *__pyx_kp_s_1;
static PyObject *__pyx_kp_s_3;
static PyObject *__pyx_kp_u_5;
static PyObject *__pyx_kp_u_6;
static PyObject *__pyx_n_s__MemoryError;
static PyObject *__pyx_n_s__OverflowError;
static PyObject *__pyx_n_s__RuntimeError;
static PyObject *__pyx_n_s____main__;
static PyObject *__pyx_n_s____test__;
static PyObject *__pyx_n_s__decode_int;
static PyObject *__pyx_n_s__encode_int;
static PyObject *__pyx_n_s__read_uchar;
static PyObject *__pyx_n_s__sign;
static PyObject *__pyx_n_s__stream;
static PyObject *__pyx_k_2;

/* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":21
 * 
 * 
 * cdef Py_ssize_t _encode_int(long i, char **buf) except? -1:             # <<<<<<<<<<<<<<
 *     # Use typecasting to get the twos complement representation of i
 *     cdef unsigned long n = (<unsigned long*>(<void *>(&i)))[0]
 */

static  Py_ssize_t __pyx_f_6cpyamf_4amf3__encode_int(long __pyx_v_i, char **__pyx_v_buf) {
  unsigned long __pyx_v_n;
  Py_ssize_t __pyx_v_size;
  unsigned long __pyx_v_real_value;
  char __pyx_v_changed;
  unsigned char __pyx_v_count;
  char *__pyx_v_bytes;
  Py_ssize_t __pyx_r;
  int __pyx_t_1;
  __Pyx_RefNannySetupContext("_encode_int");

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":23
 * cdef Py_ssize_t _encode_int(long i, char **buf) except? -1:
 *     # Use typecasting to get the twos complement representation of i
 *     cdef unsigned long n = (<unsigned long*>(<void *>(&i)))[0]             # <<<<<<<<<<<<<<
 * 
 *     cdef Py_ssize_t size = 0
 */
  __pyx_v_n = (((unsigned long *)((void *)(&__pyx_v_i)))[0]);

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":25
 *     cdef unsigned long n = (<unsigned long*>(<void *>(&i)))[0]
 * 
 *     cdef Py_ssize_t size = 0             # <<<<<<<<<<<<<<
 *     cdef unsigned long real_value = n
 *     cdef char changed = 0
 */
  __pyx_v_size = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":26
 * 
 *     cdef Py_ssize_t size = 0
 *     cdef unsigned long real_value = n             # <<<<<<<<<<<<<<
 *     cdef char changed = 0
 *     cdef unsigned char count = 0
 */
  __pyx_v_real_value = __pyx_v_n;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":27
 *     cdef Py_ssize_t size = 0
 *     cdef unsigned long real_value = n
 *     cdef char changed = 0             # <<<<<<<<<<<<<<
 *     cdef unsigned char count = 0
 *     cdef char *bytes = NULL
 */
  __pyx_v_changed = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":28
 *     cdef unsigned long real_value = n
 *     cdef char changed = 0
 *     cdef unsigned char count = 0             # <<<<<<<<<<<<<<
 *     cdef char *bytes = NULL
 * 
 */
  __pyx_v_count = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":29
 *     cdef char changed = 0
 *     cdef unsigned char count = 0
 *     cdef char *bytes = NULL             # <<<<<<<<<<<<<<
 * 
 *     if n > 0x1fffff:
 */
  __pyx_v_bytes = NULL;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":31
 *     cdef char *bytes = NULL
 * 
 *     if n > 0x1fffff:             # <<<<<<<<<<<<<<
 *         size = 4
 *         bytes = <char *>PyMem_Malloc(size)
 */
  __pyx_t_1 = (__pyx_v_n > 0x1fffff);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":32
 * 
 *     if n > 0x1fffff:
 *         size = 4             # <<<<<<<<<<<<<<
 *         bytes = <char *>PyMem_Malloc(size)
 *         changed = 1
 */
    __pyx_v_size = 4;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":33
 *     if n > 0x1fffff:
 *         size = 4
 *         bytes = <char *>PyMem_Malloc(size)             # <<<<<<<<<<<<<<
 *         changed = 1
 *         n = n >> 1
 */
    __pyx_v_bytes = ((char *)PyMem_Malloc(__pyx_v_size));

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":34
 *         size = 4
 *         bytes = <char *>PyMem_Malloc(size)
 *         changed = 1             # <<<<<<<<<<<<<<
 *         n = n >> 1
 *         bytes[count] = 0x80 | ((n >> 21) & 0xff)
 */
    __pyx_v_changed = 1;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":35
 *         bytes = <char *>PyMem_Malloc(size)
 *         changed = 1
 *         n = n >> 1             # <<<<<<<<<<<<<<
 *         bytes[count] = 0x80 | ((n >> 21) & 0xff)
 *         count += 1
 */
    __pyx_v_n = (__pyx_v_n >> 1);

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":36
 *         changed = 1
 *         n = n >> 1
 *         bytes[count] = 0x80 | ((n >> 21) & 0xff)             # <<<<<<<<<<<<<<
 *         count += 1
 * 
 */
    (__pyx_v_bytes[__pyx_v_count]) = (0x80 | ((__pyx_v_n >> 21) & 0xff));

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":37
 *         n = n >> 1
 *         bytes[count] = 0x80 | ((n >> 21) & 0xff)
 *         count += 1             # <<<<<<<<<<<<<<
 * 
 *     if n > 0x3fff:
 */
    __pyx_v_count += 1;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":39
 *         count += 1
 * 
 *     if n > 0x3fff:             # <<<<<<<<<<<<<<
 *         if size == 0:
 *             size = 3
 */
  __pyx_t_1 = (__pyx_v_n > 0x3fff);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":40
 * 
 *     if n > 0x3fff:
 *         if size == 0:             # <<<<<<<<<<<<<<
 *             size = 3
 *             bytes = <char *>PyMem_Malloc(size)
 */
    __pyx_t_1 = (__pyx_v_size == 0);
    if (__pyx_t_1) {

      /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":41
 *     if n > 0x3fff:
 *         if size == 0:
 *             size = 3             # <<<<<<<<<<<<<<
 *             bytes = <char *>PyMem_Malloc(size)
 * 
 */
      __pyx_v_size = 3;

      /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":42
 *         if size == 0:
 *             size = 3
 *             bytes = <char *>PyMem_Malloc(size)             # <<<<<<<<<<<<<<
 * 
 *         bytes[count] = 0x80 | ((n >> 14) & 0xff)
 */
      __pyx_v_bytes = ((char *)PyMem_Malloc(__pyx_v_size));
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":44
 *             bytes = <char *>PyMem_Malloc(size)
 * 
 *         bytes[count] = 0x80 | ((n >> 14) & 0xff)             # <<<<<<<<<<<<<<
 *         count += 1
 * 
 */
    (__pyx_v_bytes[__pyx_v_count]) = (0x80 | ((__pyx_v_n >> 14) & 0xff));

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":45
 * 
 *         bytes[count] = 0x80 | ((n >> 14) & 0xff)
 *         count += 1             # <<<<<<<<<<<<<<
 * 
 *     if n > 0x7f:
 */
    __pyx_v_count += 1;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":47
 *         count += 1
 * 
 *     if n > 0x7f:             # <<<<<<<<<<<<<<
 *         if size == 0:
 *             size = 2
 */
  __pyx_t_1 = (__pyx_v_n > 0x7f);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":48
 * 
 *     if n > 0x7f:
 *         if size == 0:             # <<<<<<<<<<<<<<
 *             size = 2
 *             bytes = <char *>PyMem_Malloc(size)
 */
    __pyx_t_1 = (__pyx_v_size == 0);
    if (__pyx_t_1) {

      /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":49
 *     if n > 0x7f:
 *         if size == 0:
 *             size = 2             # <<<<<<<<<<<<<<
 *             bytes = <char *>PyMem_Malloc(size)
 * 
 */
      __pyx_v_size = 2;

      /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":50
 *         if size == 0:
 *             size = 2
 *             bytes = <char *>PyMem_Malloc(size)             # <<<<<<<<<<<<<<
 * 
 *         bytes[count] = 0x80 | ((n >> 7) & 0xff)
 */
      __pyx_v_bytes = ((char *)PyMem_Malloc(__pyx_v_size));
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":52
 *             bytes = <char *>PyMem_Malloc(size)
 * 
 *         bytes[count] = 0x80 | ((n >> 7) & 0xff)             # <<<<<<<<<<<<<<
 *         count += 1
 * 
 */
    (__pyx_v_bytes[__pyx_v_count]) = (0x80 | ((__pyx_v_n >> 7) & 0xff));

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":53
 * 
 *         bytes[count] = 0x80 | ((n >> 7) & 0xff)
 *         count += 1             # <<<<<<<<<<<<<<
 * 
 *     if changed == 1:
 */
    __pyx_v_count += 1;
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":55
 *         count += 1
 * 
 *     if changed == 1:             # <<<<<<<<<<<<<<
 *         n = real_value
 * 
 */
  __pyx_t_1 = (__pyx_v_changed == 1);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":56
 * 
 *     if changed == 1:
 *         n = real_value             # <<<<<<<<<<<<<<
 * 
 *     if size == 0:
 */
    __pyx_v_n = __pyx_v_real_value;
    goto __pyx_L8;
  }
  __pyx_L8:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":58
 *         n = real_value
 * 
 *     if size == 0:             # <<<<<<<<<<<<<<
 *         size = 1
 * 
 */
  __pyx_t_1 = (__pyx_v_size == 0);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":59
 * 
 *     if size == 0:
 *         size = 1             # <<<<<<<<<<<<<<
 * 
 *         bytes = <char *>PyMem_Malloc(size)
 */
    __pyx_v_size = 1;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":61
 *         size = 1
 * 
 *         bytes = <char *>PyMem_Malloc(size)             # <<<<<<<<<<<<<<
 * 
 *     if n > 0x1fffff:
 */
    __pyx_v_bytes = ((char *)PyMem_Malloc(__pyx_v_size));
    goto __pyx_L9;
  }
  __pyx_L9:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":63
 *         bytes = <char *>PyMem_Malloc(size)
 * 
 *     if n > 0x1fffff:             # <<<<<<<<<<<<<<
 *         bytes[count] = n & 0xff
 *     else:
 */
  __pyx_t_1 = (__pyx_v_n > 0x1fffff);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":64
 * 
 *     if n > 0x1fffff:
 *         bytes[count] = n & 0xff             # <<<<<<<<<<<<<<
 *     else:
 *         bytes[count] = n & 0x7f
 */
    (__pyx_v_bytes[__pyx_v_count]) = (__pyx_v_n & 0xff);
    goto __pyx_L10;
  }
  /*else*/ {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":66
 *         bytes[count] = n & 0xff
 *     else:
 *         bytes[count] = n & 0x7f             # <<<<<<<<<<<<<<
 * 
 *     buf[0] = bytes
 */
    (__pyx_v_bytes[__pyx_v_count]) = (__pyx_v_n & 0x7f);
  }
  __pyx_L10:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":68
 *         bytes[count] = n & 0x7f
 * 
 *     buf[0] = bytes             # <<<<<<<<<<<<<<
 * 
 *     return size
 */
  (__pyx_v_buf[0]) = __pyx_v_bytes;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":70
 *     buf[0] = bytes
 * 
 *     return size             # <<<<<<<<<<<<<<
 * 
 * cdef int _decode_int(cBufferedByteStream stream, long *ret, int sign=0) except? -1:
 */
  __pyx_r = __pyx_v_size;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":72
 *     return size
 * 
 * cdef int _decode_int(cBufferedByteStream stream, long *ret, int sign=0) except? -1:             # <<<<<<<<<<<<<<
 *     cdef int n = 0
 *     cdef long result = 0
 */

static  int __pyx_f_6cpyamf_4amf3__decode_int(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *__pyx_v_stream, long *__pyx_v_ret, struct __pyx_opt_args_6cpyamf_4amf3__decode_int *__pyx_optional_args) {
  int __pyx_v_sign = ((int)0);
  int __pyx_v_n;
  long __pyx_v_result;
  unsigned char __pyx_v_b;
  int __pyx_r;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  int __pyx_t_4;
  __Pyx_RefNannySetupContext("_decode_int");
  if (__pyx_optional_args) {
    if (__pyx_optional_args->__pyx_n > 0) {
      __pyx_v_sign = __pyx_optional_args->sign;
    }
  }
  __Pyx_INCREF((PyObject *)__pyx_v_stream);

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":73
 * 
 * cdef int _decode_int(cBufferedByteStream stream, long *ret, int sign=0) except? -1:
 *     cdef int n = 0             # <<<<<<<<<<<<<<
 *     cdef long result = 0
 *     cdef unsigned char b
 */
  __pyx_v_n = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":74
 * cdef int _decode_int(cBufferedByteStream stream, long *ret, int sign=0) except? -1:
 *     cdef int n = 0
 *     cdef long result = 0             # <<<<<<<<<<<<<<
 *     cdef unsigned char b
 * 
 */
  __pyx_v_result = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":77
 *     cdef unsigned char b
 * 
 *     if stream.read_uchar(&b) == -1:             # <<<<<<<<<<<<<<
 *         return -1
 * 
 */
  __pyx_t_1 = ((struct __pyx_vtabstruct_6cpyamf_4util_cBufferedByteStream *)__pyx_v_stream->__pyx_vtab)->read_uchar(__pyx_v_stream, (&__pyx_v_b)); if (unlikely(__pyx_t_1 == -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_t_2 = (__pyx_t_1 == -1);
  if (__pyx_t_2) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":78
 * 
 *     if stream.read_uchar(&b) == -1:
 *         return -1             # <<<<<<<<<<<<<<
 * 
 *     while b & 0x80 != 0 and n < 3:
 */
    __pyx_r = -1;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":80
 *         return -1
 * 
 *     while b & 0x80 != 0 and n < 3:             # <<<<<<<<<<<<<<
 *         result <<= 7
 *         result |= b & 0x7f
 */
  while (1) {
    __pyx_t_2 = ((__pyx_v_b & 0x80) != 0);
    if (__pyx_t_2) {
      __pyx_t_3 = (__pyx_v_n < 3);
      __pyx_t_4 = __pyx_t_3;
    } else {
      __pyx_t_4 = __pyx_t_2;
    }
    if (!__pyx_t_4) break;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":81
 * 
 *     while b & 0x80 != 0 and n < 3:
 *         result <<= 7             # <<<<<<<<<<<<<<
 *         result |= b & 0x7f
 * 
 */
    __pyx_v_result <<= 7;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":82
 *     while b & 0x80 != 0 and n < 3:
 *         result <<= 7
 *         result |= b & 0x7f             # <<<<<<<<<<<<<<
 * 
 *         if stream.read_uchar(&b) == -1:
 */
    __pyx_v_result |= (__pyx_v_b & 0x7f);

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":84
 *         result |= b & 0x7f
 * 
 *         if stream.read_uchar(&b) == -1:             # <<<<<<<<<<<<<<
 *             return -1
 * 
 */
    __pyx_t_1 = ((struct __pyx_vtabstruct_6cpyamf_4util_cBufferedByteStream *)__pyx_v_stream->__pyx_vtab)->read_uchar(__pyx_v_stream, (&__pyx_v_b)); if (unlikely(__pyx_t_1 == -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_t_4 = (__pyx_t_1 == -1);
    if (__pyx_t_4) {

      /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":85
 * 
 *         if stream.read_uchar(&b) == -1:
 *             return -1             # <<<<<<<<<<<<<<
 * 
 *         n += 1
 */
      __pyx_r = -1;
      goto __pyx_L0;
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":87
 *             return -1
 * 
 *         n += 1             # <<<<<<<<<<<<<<
 * 
 *     if n < 3:
 */
    __pyx_v_n += 1;
  }

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":89
 *         n += 1
 * 
 *     if n < 3:             # <<<<<<<<<<<<<<
 *         result <<= 7
 *         result |= b
 */
  __pyx_t_4 = (__pyx_v_n < 3);
  if (__pyx_t_4) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":90
 * 
 *     if n < 3:
 *         result <<= 7             # <<<<<<<<<<<<<<
 *         result |= b
 *     else:
 */
    __pyx_v_result <<= 7;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":91
 *     if n < 3:
 *         result <<= 7
 *         result |= b             # <<<<<<<<<<<<<<
 *     else:
 *         result <<= 8
 */
    __pyx_v_result |= __pyx_v_b;
    goto __pyx_L7;
  }
  /*else*/ {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":93
 *         result |= b
 *     else:
 *         result <<= 8             # <<<<<<<<<<<<<<
 *         result |= b
 * 
 */
    __pyx_v_result <<= 8;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":94
 *     else:
 *         result <<= 8
 *         result |= b             # <<<<<<<<<<<<<<
 * 
 *         if result & 0x10000000 != 0:
 */
    __pyx_v_result |= __pyx_v_b;

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":96
 *         result |= b
 * 
 *         if result & 0x10000000 != 0:             # <<<<<<<<<<<<<<
 *             if sign == 1:
 *                 result -= 0x20000000
 */
    __pyx_t_4 = ((__pyx_v_result & 0x10000000) != 0);
    if (__pyx_t_4) {

      /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":97
 * 
 *         if result & 0x10000000 != 0:
 *             if sign == 1:             # <<<<<<<<<<<<<<
 *                 result -= 0x20000000
 *             else:
 */
      __pyx_t_4 = (__pyx_v_sign == 1);
      if (__pyx_t_4) {

        /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":98
 *         if result & 0x10000000 != 0:
 *             if sign == 1:
 *                 result -= 0x20000000             # <<<<<<<<<<<<<<
 *             else:
 *                 result <<= 1
 */
        __pyx_v_result -= 0x20000000;
        goto __pyx_L9;
      }
      /*else*/ {

        /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":100
 *                 result -= 0x20000000
 *             else:
 *                 result <<= 1             # <<<<<<<<<<<<<<
 *                 result += 1
 * 
 */
        __pyx_v_result <<= 1;

        /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":101
 *             else:
 *                 result <<= 1
 *                 result += 1             # <<<<<<<<<<<<<<
 * 
 *     ret[0] = result
 */
        __pyx_v_result += 1;
      }
      __pyx_L9:;
      goto __pyx_L8;
    }
    __pyx_L8:;
  }
  __pyx_L7:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":103
 *                 result += 1
 * 
 *     ret[0] = result             # <<<<<<<<<<<<<<
 * 
 *     return 0
 */
  (__pyx_v_ret[0]) = __pyx_v_result;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":105
 *     ret[0] = result
 * 
 *     return 0             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_r = 0;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_AddTraceback("cpyamf.amf3._decode_int");
  __pyx_r = -1;
  __pyx_L0:;
  __Pyx_DECREF((PyObject *)__pyx_v_stream);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":108
 * 
 * 
 * def encode_int(long n):             # <<<<<<<<<<<<<<
 *     """
 *     Encode C{int}.
 */

static PyObject *__pyx_pf_6cpyamf_4amf3_encode_int(PyObject *__pyx_self, PyObject *__pyx_arg_n); /*proto*/
static char __pyx_doc_6cpyamf_4amf3_encode_int[] = "\n    Encode C{int}.\n\n    @raise OverflowError: Out of range.\n    ";
static PyObject *__pyx_pf_6cpyamf_4amf3_encode_int(PyObject *__pyx_self, PyObject *__pyx_arg_n) {
  long __pyx_v_n;
  char *__pyx_v_buf;
  Py_ssize_t __pyx_v_size;
  PyObject *__pyx_v_o = 0;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  PyObject *__pyx_t_4 = NULL;
  PyObject *__pyx_t_5 = NULL;
  Py_ssize_t __pyx_t_6;
  __Pyx_RefNannySetupContext("encode_int");
  __pyx_self = __pyx_self;
  assert(__pyx_arg_n); {
    __pyx_v_n = __Pyx_PyInt_AsLong(__pyx_arg_n); if (unlikely((__pyx_v_n == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("cpyamf.amf3.encode_int");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":114
 *     @raise OverflowError: Out of range.
 *     """
 *     if n >= 0x10000000 or n < -0x10000000:             # <<<<<<<<<<<<<<
 *         raise OverflowError("Out of range")
 * 
 */
  __pyx_t_1 = (__pyx_v_n >= 0x10000000);
  if (!__pyx_t_1) {
    __pyx_t_2 = (__pyx_v_n < -268435456);
    __pyx_t_3 = __pyx_t_2;
  } else {
    __pyx_t_3 = __pyx_t_1;
  }
  if (__pyx_t_3) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":115
 *     """
 *     if n >= 0x10000000 or n < -0x10000000:
 *         raise OverflowError("Out of range")             # <<<<<<<<<<<<<<
 * 
 *     cdef char *buf = NULL
 */
    __pyx_t_4 = PyTuple_New(1); if (unlikely(!__pyx_t_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_4);
    __Pyx_INCREF(((PyObject *)__pyx_kp_s_1));
    PyTuple_SET_ITEM(__pyx_t_4, 0, ((PyObject *)__pyx_kp_s_1));
    __Pyx_GIVEREF(((PyObject *)__pyx_kp_s_1));
    __pyx_t_5 = PyObject_Call(__pyx_builtin_OverflowError, __pyx_t_4, NULL); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_5);
    __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
    __Pyx_Raise(__pyx_t_5, 0, 0);
    __Pyx_DECREF(__pyx_t_5); __pyx_t_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":117
 *         raise OverflowError("Out of range")
 * 
 *     cdef char *buf = NULL             # <<<<<<<<<<<<<<
 *     cdef Py_ssize_t size = _encode_int(n, &buf)
 *     cdef object o = PyString_FromStringAndSize(buf, size)
 */
  __pyx_v_buf = NULL;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":118
 * 
 *     cdef char *buf = NULL
 *     cdef Py_ssize_t size = _encode_int(n, &buf)             # <<<<<<<<<<<<<<
 *     cdef object o = PyString_FromStringAndSize(buf, size)
 * 
 */
  __pyx_t_6 = __pyx_f_6cpyamf_4amf3__encode_int(__pyx_v_n, (&__pyx_v_buf)); if (unlikely(__pyx_t_6 == -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_v_size = __pyx_t_6;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":119
 *     cdef char *buf = NULL
 *     cdef Py_ssize_t size = _encode_int(n, &buf)
 *     cdef object o = PyString_FromStringAndSize(buf, size)             # <<<<<<<<<<<<<<
 * 
 *     PyMem_Free(buf)
 */
  __pyx_t_5 = PyString_FromStringAndSize(__pyx_v_buf, __pyx_v_size); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_5);
  __pyx_v_o = __pyx_t_5;
  __pyx_t_5 = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":121
 *     cdef object o = PyString_FromStringAndSize(buf, size)
 * 
 *     PyMem_Free(buf)             # <<<<<<<<<<<<<<
 * 
 *     return o
 */
  PyMem_Free(__pyx_v_buf);

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":123
 *     PyMem_Free(buf)
 * 
 *     return o             # <<<<<<<<<<<<<<
 * 
 * def decode_int(stream, sign=False):
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_o);
  __pyx_r = __pyx_v_o;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_4);
  __Pyx_XDECREF(__pyx_t_5);
  __Pyx_AddTraceback("cpyamf.amf3.encode_int");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XDECREF(__pyx_v_o);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":125
 *     return o
 * 
 * def decode_int(stream, sign=False):             # <<<<<<<<<<<<<<
 *     """
 *     Decode C{int}.
 */

static PyObject *__pyx_pf_6cpyamf_4amf3_decode_int(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6cpyamf_4amf3_decode_int[] = "\n    Decode C{int}.\n    ";
static PyObject *__pyx_pf_6cpyamf_4amf3_decode_int(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_stream = 0;
  PyObject *__pyx_v_sign = 0;
  long *__pyx_v_result;
  PyObject *__pyx_v_ret;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  struct __pyx_opt_args_6cpyamf_4amf3__decode_int __pyx_t_4;
  PyObject *__pyx_t_5 = NULL;
  PyObject *__pyx_t_6 = NULL;
  static PyObject **__pyx_pyargnames[] = {&__pyx_n_s__stream,&__pyx_n_s__sign,0};
  __Pyx_RefNannySetupContext("decode_int");
  __pyx_self = __pyx_self;
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[2] = {0,0};
    values[1] = __pyx_k_2;
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__stream);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      if (kw_args > 0) {
        PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_n_s__sign);
        if (unlikely(value)) { values[1] = value; kw_args--; }
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "decode_int") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_stream = values[0];
    __pyx_v_sign = values[1];
  } else {
    __pyx_v_sign = __pyx_k_2;
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: __pyx_v_sign = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: __pyx_v_stream = PyTuple_GET_ITEM(__pyx_args, 0);
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("decode_int", 0, 1, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("cpyamf.amf3.decode_int");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __Pyx_INCREF(__pyx_v_stream);
  __Pyx_INCREF(__pyx_v_sign);
  __pyx_v_ret = Py_None; __Pyx_INCREF(Py_None);

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":129
 *     Decode C{int}.
 *     """
 *     cdef long *result = NULL             # <<<<<<<<<<<<<<
 *     cdef object ret
 * 
 */
  __pyx_v_result = NULL;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":132
 *     cdef object ret
 * 
 *     result = <long *>PyMem_Malloc(sizeof(long *))             # <<<<<<<<<<<<<<
 * 
 *     if result == NULL:
 */
  __pyx_v_result = ((long *)PyMem_Malloc((sizeof(long *))));

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":134
 *     result = <long *>PyMem_Malloc(sizeof(long *))
 * 
 *     if result == NULL:             # <<<<<<<<<<<<<<
 *         raise MemoryError
 * 
 */
  __pyx_t_1 = (__pyx_v_result == NULL);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":135
 * 
 *     if result == NULL:
 *         raise MemoryError             # <<<<<<<<<<<<<<
 * 
 *     if _decode_int(<cBufferedByteStream>stream, result, <int>sign) == -1:
 */
    __Pyx_Raise(__pyx_builtin_MemoryError, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":137
 *         raise MemoryError
 * 
 *     if _decode_int(<cBufferedByteStream>stream, result, <int>sign) == -1:             # <<<<<<<<<<<<<<
 *         PyMem_Free(result)
 * 
 */
  __pyx_t_2 = __Pyx_PyInt_AsInt(__pyx_v_sign); if (unlikely((__pyx_t_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_t_4.__pyx_n = 1;
  __pyx_t_4.sign = ((int)__pyx_t_2);
  __pyx_t_3 = __pyx_f_6cpyamf_4amf3__decode_int(((struct __pyx_obj_6cpyamf_4util_cBufferedByteStream *)__pyx_v_stream), __pyx_v_result, &__pyx_t_4); if (unlikely(__pyx_t_3 == -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_t_1 = (__pyx_t_3 == -1);
  if (__pyx_t_1) {

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":138
 * 
 *     if _decode_int(<cBufferedByteStream>stream, result, <int>sign) == -1:
 *         PyMem_Free(result)             # <<<<<<<<<<<<<<
 * 
 *         raise RuntimeError('Unable to decode int')
 */
    PyMem_Free(__pyx_v_result);

    /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":140
 *         PyMem_Free(result)
 * 
 *         raise RuntimeError('Unable to decode int')             # <<<<<<<<<<<<<<
 * 
 *     ret = PyInt_FromLong(result[0])
 */
    __pyx_t_5 = PyTuple_New(1); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_5);
    __Pyx_INCREF(((PyObject *)__pyx_kp_s_3));
    PyTuple_SET_ITEM(__pyx_t_5, 0, ((PyObject *)__pyx_kp_s_3));
    __Pyx_GIVEREF(((PyObject *)__pyx_kp_s_3));
    __pyx_t_6 = PyObject_Call(__pyx_builtin_RuntimeError, __pyx_t_5, NULL); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_6);
    __Pyx_DECREF(__pyx_t_5); __pyx_t_5 = 0;
    __Pyx_Raise(__pyx_t_6, 0, 0);
    __Pyx_DECREF(__pyx_t_6); __pyx_t_6 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":142
 *         raise RuntimeError('Unable to decode int')
 * 
 *     ret = PyInt_FromLong(result[0])             # <<<<<<<<<<<<<<
 * 
 *     PyMem_Free(result)
 */
  __pyx_t_6 = PyInt_FromLong((__pyx_v_result[0])); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_6);
  __Pyx_DECREF(__pyx_v_ret);
  __pyx_v_ret = __pyx_t_6;
  __pyx_t_6 = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":144
 *     ret = PyInt_FromLong(result[0])
 * 
 *     PyMem_Free(result)             # <<<<<<<<<<<<<<
 * 
 *     return ret
 */
  PyMem_Free(__pyx_v_result);

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":146
 *     PyMem_Free(result)
 * 
 *     return ret             # <<<<<<<<<<<<<<
 * 
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_ret);
  __pyx_r = __pyx_v_ret;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_5);
  __Pyx_XDECREF(__pyx_t_6);
  __Pyx_AddTraceback("cpyamf.amf3.decode_int");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_ret);
  __Pyx_DECREF(__pyx_v_stream);
  __Pyx_DECREF(__pyx_v_sign);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {__Pyx_NAMESTR("encode_int"), (PyCFunction)__pyx_pf_6cpyamf_4amf3_encode_int, METH_O, __Pyx_DOCSTR(__pyx_doc_6cpyamf_4amf3_encode_int)},
  {__Pyx_NAMESTR("decode_int"), (PyCFunction)__pyx_pf_6cpyamf_4amf3_decode_int, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(__pyx_doc_6cpyamf_4amf3_decode_int)},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("amf3"),
    __Pyx_DOCSTR(__pyx_k_4), /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_s_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 0, 1, 0},
  {&__pyx_kp_s_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 0, 1, 0},
  {&__pyx_kp_u_5, __pyx_k_5, sizeof(__pyx_k_5), 0, 1, 0, 0},
  {&__pyx_kp_u_6, __pyx_k_6, sizeof(__pyx_k_6), 0, 1, 0, 0},
  {&__pyx_n_s__MemoryError, __pyx_k__MemoryError, sizeof(__pyx_k__MemoryError), 0, 0, 1, 1},
  {&__pyx_n_s__OverflowError, __pyx_k__OverflowError, sizeof(__pyx_k__OverflowError), 0, 0, 1, 1},
  {&__pyx_n_s__RuntimeError, __pyx_k__RuntimeError, sizeof(__pyx_k__RuntimeError), 0, 0, 1, 1},
  {&__pyx_n_s____main__, __pyx_k____main__, sizeof(__pyx_k____main__), 0, 0, 1, 1},
  {&__pyx_n_s____test__, __pyx_k____test__, sizeof(__pyx_k____test__), 0, 0, 1, 1},
  {&__pyx_n_s__decode_int, __pyx_k__decode_int, sizeof(__pyx_k__decode_int), 0, 0, 1, 1},
  {&__pyx_n_s__encode_int, __pyx_k__encode_int, sizeof(__pyx_k__encode_int), 0, 0, 1, 1},
  {&__pyx_n_s__read_uchar, __pyx_k__read_uchar, sizeof(__pyx_k__read_uchar), 0, 0, 1, 1},
  {&__pyx_n_s__sign, __pyx_k__sign, sizeof(__pyx_k__sign), 0, 0, 1, 1},
  {&__pyx_n_s__stream, __pyx_k__stream, sizeof(__pyx_k__stream), 0, 0, 1, 1},
  {0, 0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  __pyx_builtin_OverflowError = __Pyx_GetName(__pyx_b, __pyx_n_s__OverflowError); if (!__pyx_builtin_OverflowError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_builtin_MemoryError = __Pyx_GetName(__pyx_b, __pyx_n_s__MemoryError); if (!__pyx_builtin_MemoryError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_builtin_RuntimeError = __Pyx_GetName(__pyx_b, __pyx_n_s__RuntimeError); if (!__pyx_builtin_RuntimeError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  return 0;
  __pyx_L1_error:;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initamf3(void); /*proto*/
PyMODINIT_FUNC initamf3(void)
#else
PyMODINIT_FUNC PyInit_amf3(void); /*proto*/
PyMODINIT_FUNC PyInit_amf3(void)
#endif
{
  PyObject *__pyx_t_1 = NULL;
  PyObject *__pyx_t_2 = NULL;
  PyObject *__pyx_t_3 = NULL;
  #if CYTHON_REFNANNY
  void* __pyx_refnanny = NULL;
  __Pyx_RefNanny = __Pyx_RefNannyImportAPI("refnanny");
  if (!__Pyx_RefNanny) {
      PyErr_Clear();
      __Pyx_RefNanny = __Pyx_RefNannyImportAPI("Cython.Runtime.refnanny");
      if (!__Pyx_RefNanny)
          Py_FatalError("failed to import 'refnanny' module");
  }
  __pyx_refnanny = __Pyx_RefNanny->SetupContext("PyMODINIT_FUNC PyInit_amf3(void)", __LINE__, __FILE__);
  #endif
  __pyx_init_filenames();
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #if PY_MAJOR_VERSION < 3
  __pyx_empty_bytes = PyString_FromStringAndSize("", 0); if (unlikely(!__pyx_empty_bytes)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #else
  __pyx_empty_bytes = PyBytes_FromStringAndSize("", 0); if (unlikely(!__pyx_empty_bytes)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #endif
  /*--- Library function declarations ---*/
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("amf3"), __pyx_methods, __Pyx_DOCSTR(__pyx_k_4), 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_module_is_main_cpyamf__amf3) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_n_s____main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  __pyx_ptype_6cpyamf_4util_cBufferedByteStream = __Pyx_ImportType("cpyamf.util", "cBufferedByteStream", sizeof(struct __pyx_obj_6cpyamf_4util_cBufferedByteStream)); if (unlikely(!__pyx_ptype_6cpyamf_4util_cBufferedByteStream)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_GetVtable(__pyx_ptype_6cpyamf_4util_cBufferedByteStream->tp_dict, &__pyx_vtabptr_6cpyamf_4util_cBufferedByteStream) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_6cpyamf_4util_cIndexedCollection = __Pyx_ImportType("cpyamf.util", "cIndexedCollection", sizeof(struct __pyx_obj_6cpyamf_4util_cIndexedCollection)); if (unlikely(!__pyx_ptype_6cpyamf_4util_cIndexedCollection)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_GetVtable(__pyx_ptype_6cpyamf_4util_cIndexedCollection->tp_dict, &__pyx_vtabptr_6cpyamf_4util_cIndexedCollection) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_6cpyamf_4util_cIndexedMap = __Pyx_ImportType("cpyamf.util", "cIndexedMap", sizeof(struct __pyx_obj_6cpyamf_4util_cIndexedMap)); if (unlikely(!__pyx_ptype_6cpyamf_4util_cIndexedMap)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_GetVtable(__pyx_ptype_6cpyamf_4util_cIndexedMap->tp_dict, &__pyx_vtabptr_6cpyamf_4util_cIndexedMap) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":125
 *     return o
 * 
 * def decode_int(stream, sign=False):             # <<<<<<<<<<<<<<
 *     """
 *     Decode C{int}.
 */
  __pyx_t_1 = __Pyx_PyBool_FromLong(0); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_k_2 = __pyx_t_1;
  __Pyx_GIVEREF(__pyx_t_1);
  __pyx_t_1 = 0;

  /* "/Users/nick/projects/pyamf-git/cpyamf/amf3.pyx":1
 * # Copyright (c) 2007-2009 The PyAMF Project.             # <<<<<<<<<<<<<<
 * # See LICENSE for details.
 * 
 */
  __pyx_t_1 = PyDict_New(); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_1));
  __pyx_t_2 = PyObject_GetAttr(__pyx_m, __pyx_n_s__encode_int); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_3 = __Pyx_GetAttrString(__pyx_t_2, "__doc__");
  __Pyx_GOTREF(__pyx_t_3);
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
  if (PyDict_SetItem(__pyx_t_1, ((PyObject *)__pyx_kp_u_5), __pyx_t_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
  __pyx_t_3 = PyObject_GetAttr(__pyx_m, __pyx_n_s__decode_int); if (unlikely(!__pyx_t_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_3);
  __pyx_t_2 = __Pyx_GetAttrString(__pyx_t_3, "__doc__");
  __Pyx_GOTREF(__pyx_t_2);
  __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
  if (PyDict_SetItem(__pyx_t_1, ((PyObject *)__pyx_kp_u_6), __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_s____test__, ((PyObject *)__pyx_t_1)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(((PyObject *)__pyx_t_1)); __pyx_t_1 = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_XDECREF(__pyx_t_3);
  if (__pyx_m) {
    __Pyx_AddTraceback("init cpyamf.amf3");
    Py_DECREF(__pyx_m); __pyx_m = 0;
  } else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_ImportError, "init cpyamf.amf3");
  }
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

static const char *__pyx_filenames[] = {
  "amf3.pyx",
  "util.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        name = first_kw_arg;
        while (*name && (**name != key)) name++;
        if (*name) {
            values[name-argnames] = value;
        } else {
            #if PY_MAJOR_VERSION < 3
            if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
            #else
            if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
            #endif
                goto invalid_keyword_type;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        _PyString_Eq(**name, key)) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            _PyString_Eq(**name, key)) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb) {
    PyObject *tmp_type, *tmp_value, *tmp_tb;
    PyThreadState *tstate = PyThreadState_GET();

    tmp_type = tstate->curexc_type;
    tmp_value = tstate->curexc_value;
    tmp_tb = tstate->curexc_traceback;
    tstate->curexc_type = type;
    tstate->curexc_value = value;
    tstate->curexc_traceback = tb;
    Py_XDECREF(tmp_type);
    Py_XDECREF(tmp_value);
    Py_XDECREF(tmp_tb);
}

static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_GET();
    *type = tstate->curexc_type;
    *value = tstate->curexc_value;
    *tb = tstate->curexc_traceback;

    tstate->curexc_type = 0;
    tstate->curexc_value = 0;
    tstate->curexc_traceback = 0;
}


#if PY_MAJOR_VERSION < 3
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) Py_TYPE(type);
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }

    __Pyx_ErrRestore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

#else /* Python 3+ */

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    if (tb == Py_None) {
        tb = 0;
    } else if (tb && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto bad;
    }
    if (value == Py_None)
        value = 0;

    if (PyExceptionInstance_Check(type)) {
        if (value) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto bad;
        }
        value = type;
        type = (PyObject*) Py_TYPE(value);
    } else if (!PyExceptionClass_Check(type)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: exception class must be a subclass of BaseException");
        goto bad;
    }

    PyErr_SetObject(type, value);

    if (tb) {
        PyThreadState *tstate = PyThreadState_GET();
        PyObject* tmp_tb = tstate->curexc_traceback;
        if (tb != tmp_tb) {
            Py_INCREF(tb);
            tstate->curexc_traceback = tb;
            Py_XDECREF(tmp_tb);
        }
    }

bad:
    return;
}
#endif

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    const unsigned char neg_one = (unsigned char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned char" :
                    "value too large to convert to unsigned char");
            }
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    const unsigned short neg_one = (unsigned short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned short" :
                    "value too large to convert to unsigned short");
            }
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    const unsigned int neg_one = (unsigned int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned int" :
                    "value too large to convert to unsigned int");
            }
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    const char neg_one = (char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to char" :
                    "value too large to convert to char");
            }
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    const short neg_one = (short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to short" :
                    "value too large to convert to short");
            }
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    const int neg_one = (int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to int" :
                    "value too large to convert to int");
            }
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    const signed char neg_one = (signed char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed char" :
                    "value too large to convert to signed char");
            }
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    const signed short neg_one = (signed short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed short" :
                    "value too large to convert to signed short");
            }
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    const signed int neg_one = (signed int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed int" :
                    "value too large to convert to signed int");
            }
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
    const unsigned long neg_one = (unsigned long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned long");
                return (unsigned long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    const unsigned PY_LONG_LONG neg_one = (unsigned PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned PY_LONG_LONG");
                return (unsigned PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
    const long neg_one = (long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to long");
            return (long)-1;
        }
        return (long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to long");
                return (long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
    const PY_LONG_LONG neg_one = (PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to PY_LONG_LONG");
            return (PY_LONG_LONG)-1;
        }
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to PY_LONG_LONG");
                return (PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
    const signed long neg_one = (signed long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed long");
            return (signed long)-1;
        }
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed long");
                return (signed long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
    const signed PY_LONG_LONG neg_one = (signed PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed PY_LONG_LONG");
            return (signed PY_LONG_LONG)-1;
        }
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed PY_LONG_LONG");
                return (signed PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    PyObject *ob = PyMapping_GetItemString(dict, (char *)"__pyx_vtable__");
    if (!ob)
        goto bad;
#if PY_VERSION_HEX < 0x03010000
    *(void **)vtabptr = PyCObject_AsVoidPtr(ob);
#else
    *(void **)vtabptr = PyCapsule_GetPointer(ob, 0);
#endif
    if (!*(void **)vtabptr)
        goto bad;
    Py_DECREF(ob);
    return 0;
bad:
    Py_XDECREF(ob);
    return -1;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        __pyx_empty_bytes, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        __pyx_empty_bytes  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_unicode | t->is_str) {
            if (t->intern) {
                *t->p = PyUnicode_InternFromString(t->s);
            } else if (t->encoding) {
                *t->p = PyUnicode_Decode(t->s, t->n - 1, t->encoding, NULL);
            } else {
                *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
            }
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if ((x == Py_False) | (x == Py_None)) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


#endif /* Py_PYTHON_H */
